eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
microservice:
  cart-service:
    endpoints:
      endpoint:
        uri: http://CART-SERVICE/cart/newItem
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  customer-service:
    endpoints:
      endpoint:
        uri: http://CUSTOMER-SERVICE/
  product-service:
    endpoints:
      endpoint:
        uri: http://PRODUCT-SERVICE/